### PR TITLE
Replace cdn.polyfill.io with polyfill-fastly.io

### LINKED ISSUE #1160: Remove recommendation for polyfill.io as it is no longer considered safe to use
The README recommends 

https://github.com/Choices-js/Choices/blob/5dbea2825a5887d88d6947443f4874bb7b84cc3a/README.md?plain=1#L1115

This is no longer considered safe to use. 

See: 

- https://polykill.io/
- https://twitter.com/triblondon/status/1761852117579427975
- https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk

### PR DESCRIPTION
**Pull request by jurgenhaas**
Fixes #1160

### CODE REVIEW

**Review by lal65 — APPROVED** [review]
These changes look great to me - excellent hardening.

**Comment by alanhamlett** [comment]
IMO polyfill shouldn't even be mentioned in case someone accidentally uses the compromised domain. It's hella outdated these days, not even needed.

**Comment by alanhamlett** [comment]
It's not complete. There's still a link in the readme to the malicious domain:

https://github.com/Choices-js/Choices/pull/1162/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1110

**Comment by alanhamlett** [comment]
Use #1161 instead.

**Comment by jurgenhaas** [comment]
I'm closing this PR as the maintainer obviously isn't interested in it. The subject came a matter of urgency, but it's probably better to just avoid using this package.

**Pull request closed without merging**
