### PR TITLE
Resolve #751/#773

### LINKED ISSUE #751: Duplicate selected values after multiple re-setting choices
Hi, thank you for the cool widget! 
found a bug:
`setChoices` with replaceChoices = true and preselected choice in the data leads to nonsense duplicated value:
```html
<select multiple></select>
```
```js
const element = document.querySelector('select');
const choices = new Choices(element);

choices.setChoices([
  {label:'Choice 1', value:'1'},
  {label:'Choice 2', value:'2', selected:true},
  {label:'Choice 3', value:'3'},
], undefined, undefined, true);

choices.setChoices([
  {label:'Choice 1', value:'1'},
  {label:'Choice 2', value:'2', selected:true},
  {label:'Choice 3', value:'3'},
], undefined, undefined, true);
```
image
[demo](https://codepen.io/yurigor/pen/abbjOej)

### PR DESCRIPTION
**Pull request by jshjohnson**
## Description

Adds new `clearItems` method that can be called when using `setChoices` by passing the `replaceChoices` argument. Fixes #751 and #773.

## Types of changes

- [ ] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kl3sk** [comment]
Does this PR will born ?

**Comment by ireznik** [comment]
Issue still open and bug still existing?

**Comment by lnfel** [comment]
PLEASE PLEASE, we need this

**Comment by galievruslan** [comment]
clearChoices still doesn't work.

```
<button name="button" type="button" class="btn btn-secondary" data-action="click->check#clean"><i class="bi bi-eraser"></i> </button>

function clean(event) {
  let el = event.target.closest('form').querySelector('.form-select')
  let finded_choice_select = new Choices(el)
  finded_choice_select.clearChoices()
}
```

**Comment by Xon** [comment]
https://github.com/Choices-js/Choices/pull/1166 implements different logic around how items/choices so it should resolve this

**Pull request closed without merging**
