### PR TITLE
Consider `tab` and `esc` keys properly

### LINKED ISSUE #1234: Accessibility Bug: Filter + Search Dropdown Field Traps Focus When Using <Shift>+<Tab>
**Describe the bug:**

An accessibility issue exists with the drop-down field in the **Search and Filter** function. When users attempt to navigate backward using `<Shift>+<Tab>`, the focus does not return to the previous field. Instead, it collapses/expands the drop-down repeatedly, creating a "_focus trap_". Users must navigate forward through all subsequent `<Tab>`-able elements to return to the previous field, which disrupts keyboard navigation and hinders accessibility.

**To Reproduce:**

- Steps to reproduce the behavior:

1. Go to the **Events List** page on our staging site: [https://glump.io/list-block/](https://glump.io/list-block/).
2. Locate the **Filters** section at the top of the page.
3. Use `<Tab>` to navigate into the first and second drop-down fields ("_Category_"," _All Locations_").
4. Verify that `<Tab>` moves the focus forward and `<Shift>+<Tab>` correctly moves the focus back to the previous field or interactive element.
5. Navigate to the third field ("_Select Postal Code_") where the Search and Filter function is applied.
6. Attempt to use `<Shift>+<Tab>` to return to the previous field.

- **Observed Behavior** - instead of moving to the previous drop-down field, `<Shift>+<Tab>` causes the drop-down to collapse/expand, and the focus remains trapped within the field.

- **NOTE:** - I also encountered this same bug when using `<Tab>`/`<Shift>+<Tab>` commands in the examples provided on [https://choices-js.github.io/Choices/](https://choices-js.github.io/Choices/), under the "_Multiple select input_" section.

**Expected behavior:**

When using `<Shift>+<Tab>` in the "_Select Postal Code_" field:

- The focus should move to the previous drop-down field ("_All Locations_").
- Keyboard users should not encounter any traps or disruptions in navigation, ensuring smooth backward navigation across all fields in the section.

**Screenshots:**

- Not applicable.

**Choices version and bundle:**

- 11.0.2, choices.js

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro - version 23H2
 - Browsers - tested in: 
    - Firefox Developer Edition - version 134.0b3
    - Chrome - version 131.0.6778.86
    - Edge - version 131.0.2903.70

_**Note** - all browsers indicate they are up to date in Settings section._

**Smartphone (please complete the following information):**

- Not applicable (since this is a keyboard issue).

### PR DESCRIPTION
**Pull request by zoglo**
## Description

* Fixes #1234
* Fixes [#1209 (comment)](https://github.com/Choices-js/Choices/issues/1209#issuecomment-2416970351)

This PR fixes the weird behavior that people have when search has been disabled and you are trying to tab through.

Keys like `tab` for keyboard accessibility have not been taken into account at all, rendering keyboard navigation impossible in the current version. (Especially trying to navigate back as well when a search exists).

The dropdown stays open due to the following line not taking into account the typical behavior of Tab (focusing out) or Escape.
https://github.com/Choices-js/Choices/blob/a127f82755e85f326d929054359370a117fa173c/src/scripts/choices.ts#L1606-#L1623

## Types of changes

- [ ] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have added new tests for the bug I fixed/the new feature I added.
- [ ] I have modified existing tests for the bug I fixed/the new feature I added.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Xon** [comment]
This sadly makes #1230 much more obvious the direction key handling is buggy :(

**Comment by zoglo** [comment]
> This sadly makes #1230 much more obvious the direction key handling is buggy :(

Hmm, you mean with shift + tab, right?
Should we open a new issue for that one, especially accessible wise?

There's a few more things I noticed but didn't have the time to find a proper solution for right now

**Comment by zoglo** [comment]
We could continue this in the mentioned issue as well, especially since the handling could be improved upon and there's more to handle such as shift + tab at the same time not focusing into an existing serach - I noted it down

**Comment by Xon** [comment]
A new issue to track it would be best

**Comment by Xon** [comment]
@zoglo I've opened the #1242 which appears to fix #1230
Can you see if it fixes other issues you've observed around tab-handling?

**Comment by zoglo** [comment]
> @zoglo I've opened the 1242 which appears to fix 1230 Can you see if it fixes other issues you've observed around tab-handling?

Will check tmrw after I wake up👍

**Pull request merged**
