### PR TITLE
Add option labelId to improve a11y

### PR DESCRIPTION
**Pull request by brosua**
## Description

A new option labelId was introduced. If this option is set, the choices element contains aria-labeledby. If someone uses a screenreader, he/she will get information, which label is associated with the focused input.

This fixes https://github.com/Choices-js/Choices/issues/937.

## Types of changes

- [ ] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mtriff** [comment]
I haven't done a full review yet, but this seems great! Could we enable this by default if the choices element has an id? I'm not very familiar with using aria-labeledby in real world use cases, so I'm not sure if it's safe to make that assumption.

**Comment by brosua** [comment]
Hi @mtriff ,
yes, that is possible. The id of the passed element can be determined and used by aria-labeledby. The choices option would override this value (edge cases).

**Comment by ridinghoodmedia** [comment]
Is this codebase being maintained?

**Comment by mtriff** [comment]
@ridinghoodmedia This repo is being maintained. Still waiting for a rebase of this PR and the change to enable this functionality by default before merging.

**Comment by ridinghoodmedia** [comment]
@mtriff ok great thank you

**Comment by mtriff** [comment]
@brosua, sorry for the delay. I just realized I never fully reviewed this. It looks good, I'd like to see the following before merging:

- Rebase on the latest version of `master`
- Add functionality to automatically set `labelId` if the passed element has an `id` attribute
- Add tests confirming that the `labelId` is automatically set, as well as when no `id` attribute is available

**Comment by brosua** [comment]
Hi @mtriff , I thought about your idea again. 
We can´t set the `labelId` automatically. This is the `id` of the label. I doubt, that trying to identify the correct label to read the `id`, is a good idea.

**Comment by mtriff** [comment]
That makes sense to me. This needs a unit test where `labelId` is set to something before merging.

**Comment by brosua** [comment]
Hi @mtriff 
test case is added.

**Review by mtriff — APPROVED** [review]

**Comment by mtriff** [comment]
Wonderful, thanks for the contribution!

**Pull request merged**
