### PR TITLE
fix/multiple classnames

### LINKED ISSUE #832: Class names can't contain spaces
**Describe the bug**
You can't add multiple classes and separate them with spaces. This is what you get:
```
Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('bg-gray-200 p-1') contains HTML space characters, which are not valid in tokens
```
So you can't style this with tailwind. Or keep the original class and add a bootstrap class to it. The strange thing is you can do this for `container` and `containerOuter` but nothing else.

**To Reproduce**
```javascript
new Choices(element, {
  itemSelectText: '',
  removeItemButton: true,
  classNames: {
    containerOuter: 'choices bg-gray-200 focus:bg-gray-100 focus:shadow shadow-inner appearance-none rounded w-full text-gray-700 leading-tight',
    containerInner: 'py-1 px-3',
    input: 'bg-gray-200 p-1',
  },
});
```

### PR DESCRIPTION
**Pull request by gaetan-hexadog**
## Description

In some cases, we want to be able to pass multiple class names like so 'list first second'. However, this is making an error because classList.add doesn't support space.

This PR attempts to implement allowing multi-class configs for all elements across the board by allowing to pass an array of strings for classNames.

It takes into account feedbacks from PR#907 submitted by @mikebronner

Fix #832 #889 

## Types of changes

- [ ] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have added new tests for the bug I fixed/the new feature I added.
- [x] I have modified existing tests for the bug I fixed/the new feature I added.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mtriff** [comment]
Thanks for this! Can you merge the latest version of `master` into this branch? After that I will review it.

**Comment by gaetan-hexadog** [comment]
> Thanks for this! Can you merge the latest version of `master` into this branch? After that I will review it.

Done ;-)

**Comment by ezitisitis** [comment]
I have a feeling that when @mtriff will get back to this, @gaetan-hexadog will need to merge latest `master` once again 🤣

**Comment by gaetan-hexadog** [comment]
@mtriff let me know when you'll be able to merge this PR so I can merge the latest version of `master` before (don't want to do it if you're not going to merge it quickly) ;-)

**Comment by btmluiz** [comment]
Hey, does anyone know when this PR will be merged?

**Comment by ammaraslam10** [comment]
+1

**Comment by KarelBrijs** [comment]
+1

**Comment by J2-Tech** [comment]
+1

**Comment by otherprod** [comment]
Please come  back, we need the multiple class override, thx

**Comment by MeetJF** [comment]
We need this

**Comment by liamseys** [comment]
@gaetan-hexadog Whats with this?

**Comment by gaetan-hexadog** [comment]
> @gaetan-hexadog Whats with this?

No news from the repo'd owner. I won't work on it for the third time if I don't have the insurance it will be merged quickly.
Feel free to use my PR if you want.

**Comment by ammaraslam10** [comment]
There should be a protocol for when the owner stops responding for more than a year...

**Comment by Xon** [comment]
Thanks! Implemented as part of #1166

**Pull request closed without merging**
