### PR TITLE
[BUGFIX] Correct evaluation of HTML custom properties and JSON support

### LINKED ISSUE #982: use  data-custom-properties
hi, i have html select

```
<select>
  <option value="Test1" data-custom-properties="test">Test1</option>
  <option value="Test2" data-custom-properties="test">Test2</option>
  <option value="Test3" data-custom-properties="test">Test3</option>
</select>
```

i try get data-custom-properties after change

```
document.querySelectorAll("select[name=operation]").forEach(function(element) { 
        element.addEventListener("change", (event) => {
            var show_droplist = event.target.selectedOptions[0].attributes;
            console.log(show_droplist);
            
        });       
    });
```

and show_droplist have data-custom-properties:
`value: "[object Object]"`

how get data attr from change options?

### PR DESCRIPTION
**Pull request by brosua**
## Description

The data attribute was mispelled. Also I added a logic to parse JSON, if multiple custom attributes have to be added. 
It fixes #982.

## Types of changes

- [ ] Chore (tooling change or documentation change)
- [ ] Refactor (non-breaking change which maintains existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have added new tests for the bug I fixed/the new feature I added.
- [ ] I have modified existing tests for the bug I fixed/the new feature I added.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mtriff** [comment]
Thanks! This will need unit tests for the new function you added and some e2e tests for each input type. It looks like you need to run the linter as well.

**Comment by mtriff** [comment]
@brosua are you still interested in getting this merged?

**Comment by brosua** [comment]
Yes, I will try to update the MR this week

**Comment by brosua** [comment]
Hello @mtriff , you can check the updated MR.

**Comment by Lewke** [comment]
awaiting this, really need the functionality, thanks for fixing it :)

**Comment by reimax** [comment]
awaiting this pr

**Review by Nugjii — DISMISSED** [review]

**Comment by Nugjii** [comment]
Awaiting this PR, please review and merge.

**Comment by mtriff** [comment]
Hello all, sorry for the long delay in getting this merged. I'd like to get this into the next release as well!

Taking a look at the branch, it still needs an e2e test. I've been testing it out locally and it looks like JSON custom properties breaks search with Fuse.js (errors in the console). It looks like this might be fixed by upgrading dependencies, but I haven't had a chance to look into it further.

**Review by mtriff — APPROVED** [review]

**Review by mtriff — APPROVED** [review]

**Comment by mtriff** [comment]
Thank you for the contribution @brosua!

**Pull request merged**
